language: python
python:
  - "2.7"
  - "3.4"
  # Note: nightly is a little *too* cutting edge
  # - "nightly"
# command to install dependencies
install: "pip install -r dev-requirements.txt"
# command to run tests
script: nosetests
