language: python
python:
    - "2.7"
    - "3.4"
env:
    global:
        travis=1
        DATASTORE_HOST="http://localhost:8080"
        DATASTORE_DATASET="gcd-data"

# we have some dev dependencies to install, and we also need to run dynalite for
# our testing. See run_dynalite, but we just use supervisord to run dynalite and
sudo: false
install:
    - pip install --upgrade -r dev-requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install --upgrade -r dev-requirements-27.txt; fi
    - ./tests/start_ci_services.sh

# command to run tests
script: nosetests
