language: python
python:
    - "2.7"
    - "3.4"
env:
    global:
        travis=1  # Yes, docs say that they define this, but it's missing

# command to install dependencies
install: "pip install -r dev-requirements.txt"

# command to run tests
script: nosetests
